scopesByFenceName =
  'bash': 'source.shell'
  'c': 'source.c'
  'c++': 'source.cpp'
  'coffee': 'source.coffee'
  'coffee-script': 'source.coffee'
  'coffeescript': 'source.coffee'
  'cpp': 'source.cpp'
  'cs': 'source.cs'
  'csharp': 'source.cs'
  'css': 'source.css'
  'erlang': 'source.erl'
  'go': 'source.go'
  'html': 'text.html.basic'
  'java': 'source.java'
  'javascript': 'source.js'
  'js': 'source.js'
  'json': 'source.json'
  'less': 'source.less'
  'mustache': 'text.html.mustache'
  'objc': 'source.objc'
  'objective-c': 'source.objc'
  'php': 'text.html.php'
  'powershell': 'source.powershell'
  'ps1': 'source.powershell'
  'py': 'source.python'
  'python': 'source.python'
  'rb': 'source.ruby'
  'ruby': 'source.ruby'
  'sass': 'source.sass'
  'scss': 'source.css.scss'
  'sh': 'source.shell'
  'text': 'text.plain'
  'toml': 'source.toml'
  'ts': 'source.ts'
  'typescript': 'source.ts'
  'xml': 'text.xml'
  'yaml': 'source.yaml'
  'yml': 'source.yaml'

module.exports =
  scopeForFenceName: (fenceName) ->
    fenceName = fenceName.toLowerCase()
    scopesByFenceName[fenceName] ? "source.#{fenceName}"
